spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRE_TIME}

springdoc:
  api-docs:
    path: /api-docs




